apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ZOOKEEPER_SERVER_ID # 주키퍼를 식별하는 아이디로 유일한 값, 1개의 주키퍼를 사용할 예정이라 없어도 문제 없음
              value: {{ .Values.zookeeper.serverId | quote }}
            - name: ZOOKEEPER_CLIENT_PORT # 주키퍼 포트, 기본 포트로 2181 사용
              value: {{ .Values.zookeeper.clientPort | quote }}
            - name: ZOOKEEPER_TICK_TIME # 클러스터를 구성할 때 동기화를 위한 기본 틱 타임
              value: {{ .Values.zookeeper.tickTime | quote }}
            - name: ZOOKEEPER_INIT_LIMIT
              value: {{ .Values.zookeeper.initLimit | quote }}
            - name: ZOOKEEPER_SYNC_LIMIT
              value: {{ .Values.zookeeper.syncLimit | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: client
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10 
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: client
  clusterIP: None
  selector:
    app: zookeeper
