replicaCount: 1

image:
  repository: confluentinc/cp-zookeeper
  tag: "6.2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 2181

zookeeper:
  serverId: 1
  clientPort: 2181
  tickTime: 2000
  initLimit: 5
  syncLimit: 2
